[package]
name = "drino"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.77"
reqwest = { version = "0.11.24", features = ["stream"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_yaml = "0.9.31"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
tokio-util = "0.7.10"
url = { version = "2.5.0", features = ["serde"] }
futures = { version = "0.3.30", features = [] }
thiserror = "1.0.56"
tempfile = "3.10.0"
itertools = "0.12.1"
smartstring = "1.0.1"
log = "0.4"
env_logger = "0.11.2"
zip = { version = "0.6.6", default-features = false, features = ["deflate"] }

[dependencies.polars]
version = "0.38.1"
features = ["parquet", "streaming", "lazy", "decompress", "csv", "semi_anti_join", "list_eval"]

[profile.release]
target-cpu = "native"