[package]
name = "visualization"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-files = "0.6.6"
actix-web = "4.9.0"
serde = { version = "1.0.196", features = ["derive"] }
