[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.8"
log = "0.4.22"
chrono = { workspace = true }
serde = { version = "1.0.210", features = ["derive"] }
url = { version = "2.5.0", features = ["serde"] }
reqwest = { version = "0.12.5", features = ["stream"] }
